title: tinoSwe
subtitle: Personal DevOps
description: "My Jekyll site on GitHub Pages."
email: "xx@yy.zz"
future: true
categories:
  - tech
  - tinoSwe
collections:
  posts:
    output: true
    permalink: /:categories/:title
plugins:
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/blog/:name/'
