title: tinoSwe
subtitle: personal DevOps
description: "My Jekyll site on GitHub Pages."
email: "xx@yy.zz"
twitter_username: tinoSwe
github_username: tinoSwe
future: true
collections:
  posts:
    output: true
    permalink: /:categories/:title
categories:
  - tech
  - tinoSwe
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
